name: Publish Td-Base Image

on:
  push:
    tags:
      - 'td-*'

jobs:
  mvnBuild:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build And Publish
        run: |
          bash mvnw -T 1C install
          bash mvnw -T 1C -pl ktlib-td-core exec:java
          mv libs/libtdjni*.so ktlib-td-core/libtdjni.so
          docker login docker.pkg.github.com -u $GITHUB_ACTOR -p "${{ secrets.GITHUB_TOKEN }}"
          docker build -t td-base ktlib-td-core
          tag="${{ github.ref }}"
          tag=${tag/"refs/tags/"/}
          docker tag td-base docker.pkg.github.com/nekohasekai/ktlib/td-base:$tag
          docker push docker.pkg.github.com/nekohasekai/ktlib/td-base:$tag